### ISSUE TITLE
meet error when building

### ISSUE THREAD

**Issue by Yixin-Gong** [limbo018/DREAMPlace#133]
```bash
[ 75%] Building CXX object thirdparty/OpenTimer/CMakeFiles/util.dir/unittest/utility.cpp.o
cd /home/eric/Desktop/DREAMPlace/build/thirdparty/OpenTimer && /usr/bin/c++ -D_GLIBCXX_USE_CXX11_ABI=0 -I/home/eric/Desktop/DREAMPlace/thirdparty/flute -I/home/eric/Desktop/DREAMPlace/thirdparty/OpenTimer -fPIC -O3 -DNDEBUG -std=c++17 -MD -MT thirdparty/OpenTimer/CMakeFiles/util.dir/unittest/utility.cpp.o -MF CMakeFiles/util.dir/unittest/utility.cpp.o.d -o CMakeFiles/util.dir/unittest/utility.cpp.o -c /home/eric/Desktop/DREAMPlace/thirdparty/OpenTimer/unittest/utility.cpp
In file included from /home/eric/Desktop/DREAMPlace/thirdparty/OpenTimer/unittest/utility.cpp:3:
/home/eric/Desktop/DREAMPlace/thirdparty/OpenTimer/unittest/doctest.h:4008:47: error: size of array ‘altStackMem’ is not an integral constant-expression
 4008 |         static char             altStackMem[4 * SIGSTKSZ];
      |                                               ^
make[2]: *** [thirdparty/OpenTimer/CMakeFiles/util.dir/build.make:79: thirdparty/OpenTimer/CMakeFiles/util.dir/unittest/utility.cpp.o] Error 1
make[2]: Leaving directory '/home/eric/Desktop/DREAMPlace/build'
make[1]: *** [CMakeFiles/Makefile2:3717: thirdparty/OpenTimer/CMakeFiles/util.dir/all] Error 2
make[1]: Leaving directory '/home/eric/Desktop/DREAMPlace/build'
make: *** [Makefile:139: all] Error 2
```

In latest release version 4.0.0,I met this error when building.

**Comment by enzoleo** [comment]
I believe this is due to your operating system. The macro `SIGSTKSZ` is defined as the system default stack size somewhere in `glibc`. It may be defined differently on different Linux distributions so that it would no longer be recognized as a constant. Would you please share your OS and compiler information?

You may manually change `SIGSTKSZ` to a fixed constant like 8192, though this fix might not be elegant and not sure whether it would cause any further problems. We will try to find a better solution if it is indeed an OS issue.

**Comment by Yixin-Gong** [comment]
- OS:Ubuntu 22.04.2 LTS 
- Compiler:gcc version 11.3.0
Sorry for the late reply. I've been busy with the final exams these days, so I haven't tried the method you said. I'll try it after a while.

**Comment by Yixin-Gong** [comment]
> I believe this is due to your operating system. The macro `SIGSTKSZ` is defined as the system default stack size somewhere in `glibc`. It may be defined differently on different Linux distributions, and it seems to be no longer recognized as a constant on your platform. Would you please share your OS and compiler information?
> 
> You may manually change `SIGSTKSZ` to a fixed constant like 8192, though this fix might not be elegant and not sure whether it would cause any further problems. We will try to find a better solution if it is indeed an OS issue.

- OS:Ubuntu 22.04.2 LTS
- Compiler:gcc version 11.3.0
Sorry for the late reply. I've been busy with the final exams these days, so I haven't tried the method you said. I'll try it after a while.

**Comment by zerzerzerz** [comment]
Hi, I meet this problem, too. And my OS is Ubuntu 22.04 and gcc version is 11.4.

**Comment by Yixin-Gong** [comment]
> Hi, I meet this problem, too. And my OS is Ubuntu 22.04 and gcc version is 11.4.

I fixed it by changing SGSTKSZ to 8192.lol

**Comment by Pxx-X** [comment]
> > Hi, I meet this problem, too. And my OS is Ubuntu 22.04 and gcc version is 11.4.
> 
> I fixed it by changing SIGSTKSZ to 8192.lol

Thank you, I also fixed it by changing SIGSTKSZ to 8192, cloud you please tell me why do you set SIGSTKSZ to 8192?

**Comment by enzoleo** [comment]
@Pxx-X 8192 is just an example and widely used. `SIGSTKSZ` is no longer recognized as a constant from `glibc2.34`, and that's why you meet such an error on Ubuntu 22.04. `OpenTimer` integrated the older version of `doctest` which required a constant `SIGSTKSZ` and they had already fixed it. See: https://github.com/enzoleo/OpenTimer/pull/1. The third-party version will be upgraded later after some check on Ubuntu 22.04.
