### ISSUE TITLE
Hypergraph Details

### ISSUE THREAD

**Issue by jeshu54** [limbo018/DREAMPlace#30]
@limbo018 Hello,

I want to understand how I can check the hypergraph edges and nodes of any design. I want to check the mapping and how we can implement our hyper graph using dream place. Can you please tell me where should I start looking?

Thanks,
Jeshu

**Comment by jeshu54** [comment]
@limbo018 
So far I was able to find the files that contains the nodes and nets of the design, however, I am not able to understand how I can translate it to a sparse matrix. Also if I have my own design how I can map the nodes and nets. Could you please help me here?

**Comment by limbo018** [comment]
Here is the description about the bookshelf format. 
http://vlsicad.eecs.umich.edu/BK/ISPD06bench/BookshelfFormat.txt

If you want to directly access the hypergraph, you can check following members in PlaceDB.py

## storing information of pins in each node ##
flat_node2pin_map
flat_node2pin_start_map # these two arrays are a flat version of vector<vector<int>>
pin2node_map # map pin id to its node id 

## storing information of pins in each net ##
flat_net2pin_map
flat_net2pin_start_map # these two arrays are a flat version of vector<vector<int>>
pin2net_map # map pin id to its net id 

But it is safer to convert your design to bookshelf format, because direct modifying the data structures may cause unexpected behavior especially when you are not familiar with the code.

**Comment by jeshu54** [comment]
Thanks @limbo018 
How can I access the variable? I am running the code via terminal. So I am not sure how can I access these variables?

**Comment by jeshu54** [comment]
@limbo018 I am trying to call the function from placeDB.py, flatten_nested_map which is returning lat_net2pin_map, flat_net2pin_start_map.

I am trying to call the function in placer.py using the below command.

<img width="380" alt="Screen Shot 2020-08-27 at 6 14 03 PM" src="https://user-images.githubusercontent.com/60354888/91501235-3679a600-e893-11ea-82df-608c73b0e5cb.png">

Can you tell me what parameter I need to pass here in the function flatten_nested_map ?
Thanks,
Avro

**Comment by jeshu54** [comment]
@limbo018 could you please share any update? 

Thanks,
Avro

**Comment by limbo018** [comment]
I'm not able to load the images on my side. Actually, in the latest version, I have commented out  the function flat_nested_map, which is not used anywhere. If you really want to use it, you need to make sure you have the capability of making the code work. As I mentioned, it will be easier for you to generate bookshelf rather than directly modifying the variables. 

If you insist on doing that (I do not guarantee it will work without huge modification), the argument of net2pin_map is a nested array data structure, i.e., something like vector<vector<int>> in C++. You probably need to modify the function a little bit. I remember there is a small bug (I cannot recall for now), but I didn't fix as the function is not used.

**Comment by jeshu54** [comment]
@limbo018  Thank you. Yes I have been constantly facing errors while trying to run the function. So is there any other way I can access the variable data to see the arrays? I am going to use the bookshelves like you mentioned. That will be more efficient. I just wanted to understand how the code is storing the variables and wanted to check what is stored in node2pin and net2pin variables?

**Comment by limbo018** [comment]
You can print the variables. It’s in python.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jeshu54** [comment]
@limbo018  So you mean just use print(placedb.flat_net2pin_start_map) in placer.py and I should be able to get the results.

**Comment by limbo018** [comment]
Yes.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
