### ISSUE TITLE
how to use ntuplace 

### ISSUE THREAD

**Issue by hhngw** [limbo018/DREAMPlace#33]
hi, 
I have download ntuplace3 bin file  and copy to  mydir  init/thirdparty/  but :
1. when i run  ispd2005/adaptec1.json , the log show  : thirdparty/ntuplace3:  1:thirdparty/ntuplace3 : Syntax error : word unexpected ( expecting ")")  ,
2. when i run ispd2015/lefdef/mgc_superblue19.json  , the log show  : thirdparty/ntuplace_4dr or aux file NOT found. 
where down load ntuplace_4dr?

other steps of dreamplace can be run correct

tks

**Comment by limbo018** [comment]
> 1. thirdparty/ntuplace3

Did you modify the JSON file and match the path of ntuplace3 with your path, e.g., init/thirdparty/ntuplace3, or whatever else?

For ntuplace4_dr, you need to contact the authors of the NTUplace4dr paper.

**Comment by hhngw** [comment]
I have run from the install directory ,the path is  correct  , your script can find the ntuplace engine ,but occor error 
the log show : thirdparty/ntuplace3: 1:thirdparty/ntuplace3 : Syntax error : word unexpected ( expecting ")") ,

**Comment by limbo018** [comment]
You can try to run ntuplace3 standalone by directly feeding the input files required. Probably the benchmarks contain syntaxes that cannot be recognized by ntuplace3. Can you open the input files and check the lines report problems?

**Comment by hhngw** [comment]
I have run ntuplace3 standalone by directly in ubuntu18.04 terminal ：
sudo thirdparty/ntuplace3 -aux benchmarks/ispd2005/xx/xx.aux  -loadpl /results/xx/xx.pl  -out xx -noglobal -noleagal -nodetail
the log show : thirdparty/ntuplace3: 1:thirdparty/ntuplace3 : Syntax error : word unexpected ( expecting ")")

**Comment by limbo018** [comment]
Could you try running the binary by replacing the xx.pl with the original xx.pl? Like following, 
thirdparty/ntuplace3 -aux benchmarks/ispd2005/xx/xx.aux -loadpl benchmarks/ispd2005/xx/xx.pl -out xx 

If it works, then it means there is syntax mismatch in the dumped xx.pl. Otherwise, something might be wrong with the ntuplace3 binary.

**Comment by hhngw** [comment]
It  cannot work when I run by the ispd2005  file ，the binary has been compiled in 2012 . maybe incompatible with ubuntu18.04 or gcc7.5
Thank you~

**Comment by ybj-catherine** [comment]
> hi, I have download ntuplace3 bin file and copy to mydir init/thirdparty/ but :
> 
> 1. when i run  ispd2005/adaptec1.json , the log show  : thirdparty/ntuplace3:  1:thirdparty/ntuplace3 : Syntax error : word unexpected ( expecting ")")  ,
> 2. when i run ispd2015/lefdef/mgc_superblue19.json  , the log show  : thirdparty/ntuplace_4dr or aux file NOT found.
>    where down load ntuplace_4dr?
> 
> other steps of dreamplace can be run correct
> 
> tks

hi, where did you download the ntuplace3 bin file? I also need detailed placement but did not find a proper file assinged to params.detailed_place_engine shown in the code

**Comment by limbo018** [comment]
Hi, the binaries for ntuplace3 and ntuplace_4dr are not in the repo, because these binaries are not developed by us and we do not have the permission to release them. You may need to ask the original authors of these work to obtain the binaries, i.e., Prof. Yao-Wen Chang's group.&nbsp;






                       
Original
                       
                     

From:"Binjie yan"< ***@***.*** &gt;;

Date:2024/9/10 0:14

To:"limbo018/DREAMPlace"< ***@***.*** &gt;;

CC:"Yibo Lin"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

Subject:Re: [limbo018/DREAMPlace] how to use ntuplace  (#33)




  
hi, I have download ntuplace3 bin file and copy to mydir init/thirdparty/ but :
  
when i run  ispd2005/adaptec1.json , the log show  : thirdparty/ntuplace3:  1:thirdparty/ntuplace3 : Syntax error : word unexpected ( expecting ")")  ,
 
when i run ispd2015/lefdef/mgc_superblue19.json  , the log show  : thirdparty/ntuplace_4dr or aux file NOT found.
 where down load ntuplace_4dr?
  
other steps of dreamplace can be run correct
 
tks
  
hi, where did you download the ntuplace3 bin file? I also need detailed placement but did not find a proper file assinged to params.detailed_place_engine shown in the code

**Comment by ybj-catherine** [comment]
> Hi, the binaries for ntuplace3 and ntuplace_4dr are not in the repo, because these binaries are not developed by us and we do not have the permission to release them. You may need to ask the original authors of these work to obtain the binaries, i.e., Prof. Yao-Wen Chang's group.&nbsp; Original From:"Binjie yan"< ***@***.*** &gt;; Date:2024/9/10 0:14 To:"limbo018/DREAMPlace"< ***@***.*** &gt;; CC:"Yibo Lin"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;; Subject:Re: [limbo018/DREAMPlace] how to use ntuplace (#33) hi, I have download ntuplace3 bin file and copy to mydir init/thirdparty/ but : when i run ispd2005/adaptec1.json , the log show : thirdparty/ntuplace3: 1:thirdparty/ntuplace3 : Syntax error : word unexpected ( expecting ")") , when i run ispd2015/lefdef/mgc_superblue19.json , the log show : thirdparty/ntuplace_4dr or aux file NOT found. where down load ntuplace_4dr? other steps of dreamplace can be run correct tks hi, where did you download the ntuplace3 bin file? I also need detailed placement but did not find a proper file assinged to params.detailed_place_engine shown in the code — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

thank you for reply!

**Comment by Dy233-hub** [comment]
hi, I also have the problem about finding ntuplace3 bin file. Could you tell me where did you download the ntuplace3 bin file? I also need detailed placement but I can't find the way to get ntuplace3.

**Comment by limbo018** [comment]
ntuplace3 is an optional external detailed placer. We did not get the permission from the original authors to release it. You can turn on ```detailed_place_flag``` (set to 1), and empty the ```detailed_place_engine``` and ```detailed_place_command``` fields. This configuration will invoke the default ABCDPlace engine for detailed placement.

**Comment by Dy233-hub** [comment]
Thank you,I'll try it later.
